---
apiVersion: v1
kind: Pod
metadata:
  name: debekdebug
  labels:
    pod: debek
spec:
  containers:
    - name: debekdebug
      image: debek/debekdebug:latest
      ports:
      - containerPort: 1234
      imagePullPolicy: Always
